kind: pipeline
name: dev-py36 

steps:
- name: test
  image: python:3.6-stretch
  commands:
  - wget -O tests/data/source.sqlite https://storage.googleapis.com/tm-geomancer/test/source.sqlite
  - ci/install.sh
  - pip install -r requirements-dev.txt
  - pytest --cov=geomancer -m "not bqtest and not slow" tests/
- name: coverage
  image: python:3.6-stretch 
  environment:
      COVERALLS_REPO_TOKEN:
          from_secret: coveralls_token
  commands:
  - pip install -r requirements-dev.txt
  - coveralls -v

---
kind: pipeline
name: dev-py37 

steps:
- name: test
  image: python:3.7-stretch
  commands:
  - wget -O tests/data/source.sqlite https://storage.googleapis.com/tm-geomancer/test/source.sqlite
  - ci/install.sh
  - pip install -r requirements-dev.txt
  - pytest -m "not bqtest and not slow" tests/

---
kind: pipeline
name: pkg-tox

steps:
- name: tox
  image: python:3.6-stretch
  commands:
  - wget -O tests/data/source.sqlite https://storage.googleapis.com/tm-geomancer/test/source.sqlite
  - ci/install.sh
  - pip install tox
  - tox

---
kind: pipeline
name: publish

steps:
- name: publish_pypi
  image: plugins/pypi
  settings:
    username: thinkdatasci
    password:
          from_secret: pypi_access
  when:
    event:
        - tag

depends_on:
    - dev-py36 
    - dev-py37
    - pkg-tox 
