kind: pipeline
name: python3.6

steps:
- name: test
  image: python:3.6-stretch
  commands:
  - wget -O tests/data/source.sqlite https://storage.googleapis.com/tm-geomancer/test/source.sqlite
  - ci/install.sh
  - pip install -r requirements-dev.txt
  - pytest -m "not bqtest and not slow" tests/
- name: publish
  image: plugins/pypi
  settings:
    username: thinkdatasci
    password:
          from_secret: pypi_access
  when:
    branch:
        - master
    ref:
        - refs/tags/v*


