language: python

dist: xenial

matrix:
  include:
  - name: "Python 3.6"
    python: "3.6"

before_install:
  - sudo ci/install.sh

install:
  - make travis

script:
  - pytest -m "not bqtest" tests/

